//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tb_asociado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_asociado()
        {
            this.tb_carrito = new HashSet<tb_carrito>();
            this.tb_factura = new HashSet<tb_factura>();
        }
    
        public int id_asociado { get; set; }
        public string id_persona { get; set; }



        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{00:##}")]
        public decimal monto_ahorro { get; set; } 
        public int id_estado { get; set; }
        public string correo_electronico { get; set; }
    
        public virtual tb_estado tb_estado { get; set; }
        public virtual tb_persona tb_persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_carrito> tb_carrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_factura> tb_factura { get; set; }
    }
}
