//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cliente()
        {
            this.tb_carrito = new HashSet<tb_carrito>();
            this.tb_factura = new HashSet<tb_factura>();
        }
    
        public int id_asociado { get; set; }
        public string id_persona { get; set; }
        public decimal monto_aprobado { get; set; }
        public string numero_tarjeta { get; set; }
        public string correo_electronico { get; set; }
        public int id_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_carrito> tb_carrito { get; set; }
        public virtual tb_estado tb_estado { get; set; }
        public virtual tb_persona tb_persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_factura> tb_factura { get; set; }
    }
}
