//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_carrito
    {
        public int id_carrito { get; set; }
        public int id_asociado { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
        public int id_estado { get; set; }
    
        public virtual tb_asociado tb_asociado { get; set; }
        public virtual tb_estado tb_estado { get; set; }
    }
}
