//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_carrito
    {
        public int id_carrito { get; set; }
        public int id_asociado { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
        public int id_estado { get; set; }
        public string id_carrito_user { get; set; }
    
        public virtual tb_asociado tb_asociado { get; set; }
        public virtual tb_estado tb_estado { get; set; }
        public virtual tb_producto tb_producto { get; set; }
    }
}
