//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_direccion
    {
        public int id_direccion { get; set; }
        public int id_provincia { get; set; }
        public string direccion_entrega { get; set; }
        public string id_usuario { get; set; }
    
        public virtual tb_provincia tb_provincia { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
