//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_direccion
    {
        public int id_direccion { get; set; }
        public int id_provincia { get; set; }
        public string direccion_entrega { get; set; }
        public string id_usuario { get; set; }
    
        public virtual tb_provincia tb_provincia { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
