//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_factura()
        {
            this.tb_detalle = new HashSet<tb_detalle>();
        }
    
        public int id_factura { get; set; }
        public int cliente_asociado { get; set; }
        public int id_direccion { get; set; }
        public int id_estado { get; set; }
        public decimal costo_total { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual tb_asociado tb_asociado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalle> tb_detalle { get; set; }
    }
}
