//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_producto()
        {
            this.tb_carrito = new HashSet<tb_carrito>();
            this.tb_detalle = new HashSet<tb_detalle>();
        }
    
        public int id_producto { get; set; }
        public string nombre_prod { get; set; }
        public decimal costo { get; set; }
        public int cantidad { get; set; }
        public string descripcion_prod { get; set; }
        public int id_categoria_prod { get; set; }
        public int id_estado { get; set; }
        public string imagen_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_carrito> tb_carrito { get; set; }
        public virtual tb_categoria tb_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalle> tb_detalle { get; set; }
        public virtual tb_estado tb_estado { get; set; }
    }
}
